
[functions.reestr-parser]
enabled = true
verify_jwt = false
import_map = "./functions/reestr-parser/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/reestr-parser/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/reestr-parser/*.html" ]

[functions.deepseek-agent]
enabled = true
verify_jwt = false
import_map = "./functions/deepseek-agent/deno.json"
entrypoint = "./functions/deepseek-agent/index.ts"
